# Generated by Django 6.1.1 on 2026-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_teacher_students_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.RemoveField(
            model_name="student",
            name="teacher_id",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="students_id",
        ),
        migrations.AddField(
            model_name="course",
            name="students_id",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="core.student"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teachers_id",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="core.teacher"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="courses_id",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="core.course"
            ),
        ),
    ]
